### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bNc326** [bNc326/guest-house-app#4]
- [x] Connect page to backend
- [x] Create dynamic booking calendar
- [x] Create dynamic api by hotel
- [x] Upgrade admin & frontend app to updated rest api
- [x] 404 page design & functionality
- [x] order success page with order id
- [x] Backend set admin validation to all endpoint
- [x]  Authentication with access & refresh token
- [x] Create Rating page
- [x] update rating with status on app
- [x] create search in <dataGrid /> on admin page
- [x] fix calendar bug when change hotel
- [x] Update Admin Hotel page with feature & extra capsule stackoverflow: https://stackoverflow.com/questions/65576629/how-to-render-react-icon-depending-on-string-from-database
